// <auto-generated />
namespace SoT.Infra.CrossCutting.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BirthDateandGendermovedfromApplicationUsertoEmployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BirthDateandGendermovedfromApplicationUsertoEmployee));
        
        string IMigrationMetadata.Id
        {
            get { return "201712240802595_BirthDate and Gender moved from ApplicationUser to Employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
