// <auto-generated />
namespace SoT.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20171123_922 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171123_922));
        
        string IMigrationMetadata.Id
        {
            get { return "201711222322182_20171123_922"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
