// <auto-generated />
namespace SoT.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20171217Genderentityadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171217Genderentityadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201712170823287_20171217 Gender entity added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
