// <auto-generated />
namespace SoT.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180110AdventurereferencetoUserremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180110AdventurereferencetoUserremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201801100415417_20180110 - Adventure reference to User removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
